name: todoapp

on:
  #push:
  #  # Trigger this workflow only on commits pushed to the main branch
  #  branches:
  #    - main
  workflow_dispatch:

# Dagger plan gets configured via client environment variables
env:
  # This needs to be unique across all of netlify.app
  APP_NAME: todoapp-dagger-devopselvis
  NETLIFY_TEAM: mickeygousset

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Deploy to Netlify
        uses: dagger/dagger-for-github@v3
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: latest
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            login
            project update
            do deploy
        env:
          # Get one from https://app.netlify.com/user/applications/personal
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
